Repository Androz2091/discord-player, pull requests merged in 2023-10, with the labels that each got.

#1823 feat: add serialization and deserialization methods
  README.md
  packages/discord-player/__test__/serde.spec.ts
  packages/discord-player/src/errors/index.ts
  packages/discord-player/src/fabric/Playlist.ts
  packages/discord-player/src/fabric/Track.ts
  packages/discord-player/src/index.ts
  packages/discord-player/src/utils/serde.ts
  packages/extractor/src/extractors/common/helper.ts
Labels: enhancement, area:main

#1824 fix(serde): remove $ from SerializedType value
  packages/discord-player/src/utils/serde.ts
Labels: enhancement, area:main

#1826 fix(hooks): throw on illegal useMainPlayer invocation
  .vscode/settings.json
  packages/adapter-local/package.json
  packages/adapter-remote/package.json
  packages/discord-player/__test__/hooks.spec.ts
  packages/discord-player/package.json
  packages/discord-player/src/errors/index.ts
  packages/discord-player/src/hooks/useMainPlayer.ts
  packages/tsconfig/package.json
  packages/utils/package.json
Labels: enhancement, area:main

#1828 fix(QueryResolver): follow known redirect uri
  packages/discord-player/__test__/QueryResolver.spec.ts
  packages/discord-player/src/Player.ts
  packages/discord-player/src/utils/QueryResolver.ts
Labels: area:main

#1829 feat(GuildQueue): add track skip reason, remove skipOnNoStream
  packages/discord-player/src/manager/GuildNodeManager.ts
  packages/discord-player/src/manager/GuildQueue.ts
  packages/discord-player/src/manager/GuildQueueHistory.ts
  packages/discord-player/src/manager/GuildQueuePlayerNode.ts
Labels: area:main

#1831 fix(QueryResolver): update apple music playlist regex
  packages/discord-player/__test__/QueryResolver.spec.ts
  packages/discord-player/src/utils/QueryResolver.ts
Labels: area:main

#1832 fix(AttachmentExtractor): set probe timeout
  packages/discord-player/src/Player.ts
  packages/discord-player/src/types/types.ts
  packages/extractor/src/extractors/AttachmentExtractor.ts
Labels: area:main, area:extractor

#1833 fix(BridgeProvider): add demuxer support
  packages/extractor/src/extractors/common/BridgeProvider.ts
Labels: area:extractor

#1834 fix(Player): enable demuxer optimization by default
  packages/discord-player/src/Player.ts
Labels: area:main

#1835 docs: update ip rotation guide page
  apps/website/src/pages/guide/_guides/youtube/ip_rotation.mdx
Labels: documentation

#1836 fix(AFilterGraph): expose current biquad filter
  packages/discord-player/src/manager/GuildQueueAudioFilters.ts
Labels: area:main

#1838 export `BridgedExtractor`
  packages/extractor/src/extractors/index.ts
Labels: area:extractor

#1840 perf: optimize debug logs
  packages/discord-player/src/Player.ts
  packages/discord-player/src/manager/GuildQueue.ts
  packages/discord-player/src/utils/PlayerEventsEmitter.ts
Labels: area:main

#1842 feat: add dynamic shuffle mode
  apps/music-bot/src/commands/shuffle.ts
  packages/discord-player/src/manager/GuildQueue.ts
  packages/discord-player/src/utils/Util.ts
Labels: area:main

#1843 feat(YoutubeExtractor): add mixes support
  apps/music-bot/src/commands/play.ts
  packages/discord-player/package.json
  packages/discord-player/src/manager/GuildQueue.ts
  packages/discord-player/src/utils/QueryResolver.ts
  packages/extractor/package.json
  packages/extractor/src/extractors/YoutubeExtractor.ts
  yarn.lock
Labels: area:main, area:extractor

#1846 feat: add bindHook function
  packages/discord-player/src/hooks/common.ts
  packages/discord-player/src/types/types.ts
Labels: area:main

#1847 feat(ExtractorExecutionContext): allow passing options via loadDefault
  apps/music-bot/src/listeners/ready.ts
  packages/discord-player/src/extractors/ExtractorExecutionContext.ts
  packages/extractor/package.json
  packages/extractor/src/extractors/common/BridgeProvider.ts
  yarn.lock
Labels: area:main, area:extractor

#1849 feat(BaseExtractor): add priority
  packages/discord-player/src/extractors/BaseExtractor.ts
  packages/discord-player/src/extractors/ExtractorExecutionContext.ts
  packages/extractor/src/extractors/AttachmentExtractor.ts
Labels: area:main, area:extractor

#1850 docs: generate documentation
  apps/website/src/data/docs.json
Labels: documentation

#1851 docs: add serialization and deserializaiton guide
  apps/website/src/pages/guide/[topic]/[page].tsx
  apps/website/src/pages/guide/_guides/faq/serialization_and_deserialization.mdx
Labels: documentation

#1853 chore: migrate to yarn v4
  .yarn/plugins/@yarnpkg/plugin-version.cjs
  .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
  .yarn/releases/yarn-3.3.1.cjs
  .yarn/releases/yarn-4.0.0.cjs
  .yarn/versions/9083f089.yml
  .yarn/versions/a3d409b8.yml
  .yarn/versions/db15b20e.yml
  .yarn/versions/f3db08fc.yml
  .yarnrc.yml
  apps/music-bot/package.json
  apps/website/package.json
  package.json
  packages/adapter-local/package.json
  packages/adapter-remote/package.json
  packages/core/package.json
  packages/discord-player/package.json
  packages/downloader/package.json
  packages/equalizer/package.json
  packages/extractor/package.json
  packages/ffmpeg/package.json
  packages/opus/package.json
  packages/tsconfig/base.json
  packages/tsconfig/package.json
  packages/utils/package.json
  packages/voice/package.json
  yarn.lock
Labels: dependencies

#1854 fix(GuildQueuePlayerNode): use @discord-player/opus
  packages/discord-player/src/manager/GuildQueuePlayerNode.ts
Labels: bug, area:main

#1863 feat(BaseExtractor): add protocols support
  apps/music-bot/src/listeners/ready.ts
  packages/discord-player/src/Player.ts
  packages/discord-player/src/extractors/BaseExtractor.ts
  packages/discord-player/src/extractors/ExtractorExecutionContext.ts
  packages/extractor/src/extractors/AppleMusicExtractor.ts
  packages/extractor/src/extractors/SoundCloudExtractor.ts
  packages/extractor/src/extractors/SpotifyExtractor.ts
  packages/extractor/src/extractors/YoutubeExtractor.ts
Labels: area:main, area:extractor

#1864 docs: add protocol example in guide
  apps/website/src/pages/guide/_guides/extractors/creating_extractor.mdx
Labels: documentation
